apiVersion: apps/v1
kind: Deployment
metadata:
  name: restaurant-app
  namespace: restaurant
spec:
  replicas: 1
  selector:
    matchLabels:
      app: restaurant-app
  template:
    metadata:
      labels:
        app: restaurant-app
    spec:
      containers:
      - name: frontend-container
        image: public.ecr.aws/u3m8u0c4/ce5-group2-frontend:latest
        imagePullPolicy: Always
        env:
          - name: HUB_HOST
            value: backend-service.restaurant
          - name: HUB_PORT
            value: "8888"
        ports:
          - containerPort: 80
          
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: restaurant
  labels:
    app: restaurant-app
spec:
  type: ClusterIP
  selector:
    app: restaurant-app
  ports:
    - name: webpage
      protocol: TCP
      port: 7778
      targetPort: 80

---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: app-service-monitor
  namespace: monitoring
  labels:
    app: prometheus
    release: prometheus
spec:
  selector:
    matchLabels:
      app: restaurant-app
  endpoints:
    - port: webpage
      interval: 30s